### ISSUE TITLE
Interested in your Drums & Filters and Seqs & Tools module sets

### ISSUE THREAD

**Issue by vogelscheiss** [AScustomWorks/Paid-Modules-Info#1]
But at $20 for each set, want to be double-sure you're committed to keeping the modules updated indefinitely with all succeeding updates to VCV Rack, so that patches I would create with them won't become obsolete.

Could you please confirm? Thanks.

**Comment by n6smith** [comment]
FWIW... I think its unreasonable, given that VCV Rack and any plugins built for it... are still in the Beta stage.. to expect future patches not to break at some point, though I realize you are asking more about future obsolescence rather than incompatibility..  Personally I make full backups of both the app, the plugin folder and the patches folder each time a major update occurs... so I can roll back at any point in time in the future when I wish to play an older patch using older versions of plugins and Rack itself.  Having said that, in my experience... AS (as well as several other of the Devs that have paid for plugins available.. such as Vult for example..)  is one of the more proactive Devs... in regards to updating his plugins to work without issues with each and every update so far... so Im not concerned that this will not continue on into the future.

**Comment by vogelscheiss** [comment]
Your point about keeping old versions of VCV Rack and plugins is reasonable. And I'm not talking about short-term broken patches but long-term reasonable maintenance.

To your point one could say that when a plugin is for an app that's in beta stage, it's perhaps a hair early to start charging for it, but that if you do, it conveys a certain tacit agreement to meet certain general expectations to stand behind your work. And I don't doubt that most developers charging for modules intend to. But I'd differ with calling the question "unreasonable," caveat emptor and all that.

**Comment by n6smith** [comment]
The same could be said for any software.... paid for or otherwise... and any Dev can promise anything but it doesn't mean they will stand by any such promises. So I guess, its a bit of a risk you take.. Having said that, for $20 .... for me, its a risk worth taking especially as I find AS plugins so useful now... and if I only got 6 months use out of them.. I'd consider I had got my money's worth! :)

**Comment by vogelscheiss** [comment]
For the developers it must be a strange combination of labor-of-love and needing to charge something. $20 here and there will pay for a few lattes, but the hours going into all this DSP must be immense. That said, having things stop working is a huge inconvenience, and you have alternatives. C'est la vie.

**Comment by AScustomWorks** [comment]
Quick answer: Yes, I'm serious about this, otherwise I wouldn't be doing it.

Please keep reading:

I think the sole existence of this public repository for the purpose of giving the users a way to open/find issues -when I say issues I mean bugs- with my paid plugins speaks a lot about the answer to your question, right?

Now, about the $20,  you imply it is a lot of money. Please consider this:

- Compare the $20 to what you usually have to pay for some vst plugins. Kind of a nice deal, isn't it?

- You are not paying for a $20 pice of software alone, you also pay for 10, 15, etc. years of programming experience in some cases, if you ask any developer to do the same work just for you, you would be paying on the thousands range easily.

- At least in my case, you are not paying for a given set of modules and that's it (as it is with some other plugins now), I plan to add new modules to each set as I see fit, so in the end you'll get more out of your $20.

I could be finishing a new release right now, with an extra module I'm working on for the Seqs & Tools plugin, but even so, I'm here answering your question.

Btw. "keeping the modules updated indefinitely with all succeeding updates to VCV Rack" may be a bit over reaching, considering the nature of software and hardware. Not that I won't try to deliver, but as you said, C'est la vie ;)

**Comment by vogelscheiss** [comment]
Freddy, I agree with everything you said. Not everyone developing modules for VCV Rack approaches it with more than casual interest, which is apparent both in their own statements and in the modules themselves.

As far as I'm concerned VCV Rack and the modules developers like you are making are together the most exciting thing I've seen in music software in a long time. The CV manipulation stuff may be running a hair ahead of some of the DSP end – there's some very nice shimmery analog modeling out there in the world – but as long as the audio is pretty solid, which it is, for me the CV stuff is where the excitement is. 

Softube Modular seems to have invested a lot in the modeling analog circuits, and it has an edge with sound quality, but it's so regally punted the interface and hobbled the basic modules that it just isn't fun to use long-term. Frankly I think Softube should become a paid vendor on the VCV Rack plugins manager page, selling their Buchla, Intellijel, 4MS, and Doepfer modules as worthy additions for VCV's much-superior interface and intense development community. (God knows whether they're actually port-able.)

I view what you're doing as a huge labor of love. For that matter, so is what I do. I also am vastly underpaid for years of experience.

As a composer I'm often stymied by the rapid pace of software obsolescence. I have a lot of film cues from a few years ago that would take hours and hours to get functioning again if they could be resurrected at all, just from the accumulated changes to Vienna Ensemble, various NI software, fx plugins etc.

With VCV Rack in beta, obsolescence can come within months.

So you're right, $20 is nothing, and it's only by getting a giant stack of $20 payments that a developer like yourself can consider yourself even minutely compensated for the time you're putting in. And VCV Rack is probably not poised to generate huge stacks of $20 payments anytime soon. So the $20 is almost like a thank you. 

The VCV Rack developer community is like a black box, so thanks very much for your response.

And since it's obvious you're highly engaged in this, I'll definitely be buying your stuff.

**Comment by AScustomWorks** [comment]
@vogelscheiss thanks ;)
I do believe Andrew made a great job at making the entry point really accesible for developers, so we all can come up with new modules pretty fast, at the expense of having a few bad ones here and there as you said, of course. Probably only free ones in any case, at least if the developer wants to make more than a few sales I think hehe.

And, I guess the big companies won't jump into vcv rack  plugin development, if they ever do, until they think is profitable enough. I bet the price point right now, may be way too low for them to even consider it. But, maybe that's the doorway for more developers with fresh ideas to join in, not so bad after all.

I'll close this issue for now if you don't mind ;)
